### PR TITLE
initial commit on backend

### PR DESCRIPTION
**Pull request by aliturgutalp**
Django app is set up. I used tutorials on django girls site to a point. DB configuration is set as PostgreSQL.

### CODE REVIEW

**Review by bartuinceQR — APPROVED** [review]

**Review by ergunsh — CHANGES_REQUESTED** [review]
Can you write an how-to install, start the server and psql instructions? @aliturgutalp

**Comment by aliturgutalp** [comment]
We need to install python3.6 and pip3. After that there is a file 'requirements.txt' for installing python. You can see the codes for starting the server on Django Girls tutorial. Find the file structures and commands on [here](https://tutorial.djangogirls.org/en/)

**Comment by ergunsh** [comment]
I think, we would like to see the instructions in here rather than going to the tutorial; can you write them to a readme file?

**Comment by ergunsh** [comment]
Also, I couldn’t see any instructions on installing postgresql and creating a user 🤔

**Comment by ergunsh** [comment]
farewell, django...

**Pull request closed without merging**
